version: '3'

services:
  web:
    image: remdex/livehelperchat-rag-embed:latest
    build: .
    ports:
      - "127.0.0.1:9710:5000"
#    volumes:
#      - ./embed.py:/app/embed.py
    restart: always